### ISSUE TITLE
How does SPIFFE handle Trust Domain collision?

### ISSUE THREAD

**Issue by mbrg** [spiffe/spiffe#116]
Hi SPIFFE team,
I'm new here, so please forgive me if this has an obvious answer.

My question is about the following paragraph from the [SVID standard](/standards/SPIFFE-ID.md):

> Trust domains are nominally self-registered, unlike public DNS there is no delegating authority that acts to assert and register a base domain to an actual legal real-world entity, or assert that legal entity has fair and due rights to any particular trust domain.

In case SPIFFE takes off and becomes a widely adopted standard, Trust Domain name collision are bound to happen. 

- How can I enable communication between my trust domain and a couple of trust domains who happen to use the same name?

- Can I rename them when I configure the federation? How would we make sure this doesn't cause confusion?

Thanks.

**Comment by spikecurtis** [comment]
Hi @mibarg I think it's fair to say that the current situation is that federation breaks if there is a trust domain name collision.

I've added this issue to the agenda for our next sig-spec meeting. You are welcome to join us for the discussion: https://goo.gl/CboVqQ

**Comment by mbrg** [comment]
Thank you very much!

**Comment by spikecurtis** [comment]
@mibarg We postponed talking about this issue because you weren't able to attend, and we didn't have our entire regular group available.  If you're able to make the next meeting, please let us know. Otherwise we'll plan to post the results of that discussion here.

**Comment by evan2645** [comment]
Hi @mbrg

Wondering if #126 has answered your question, or if you'd like to discuss this further on the SIG-Spec call?

**Comment by mbrg** [comment]
> Hi @mbrg
> 
> Wondering if #126 has answered your question, or if you'd like to discuss this further on the SIG-Spec call?

It does! Thank you
