### ISSUE TITLE
SPIFFE Bundle Format: consider to make more clear the requirements for the `use` parameter

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spiffe#121]
[Section 4.2.2](https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE_Trust_Domain_and_Bundle.md#422-public-key-use) of the SPIFFE Trust Domain and Bundle specification has the requirements for the `use` parameter in the SPIFFE Bundle Format.
While implementing a SPIFFE Bundle parser, it was not completely clear how this parameter should be treated in conformance with the standard.
In particular, the specification says:
>The `use` parameter MUST be set.

and also:

> Clients encountering unknown `use` values MUST ignore the entire JWK element.

Which does not provide clarity for the case where there is a document that has some keys with valid SPIFFE values for the `use` parameter and some with no `use` specified.
It would be good if it is clear from the standard perspective how such case should be treated by software that produces/consumes documents using the SPIFFE Bundle Format.

**Comment by spikecurtis** [comment]
I think we probably want to also instruct clients to ignore JWK elements without a `use` value.  WDYT @evan2645 ?

**Comment by evan2645** [comment]
That's my inclination as well. If we encounter a bundle with mixed types (e.g. recognized and non-recognized or missing use values), I think we should take the keys we recognize and ignore the rest. The goal of that is to lower the barrier to entry for existing JWKS servers as well as enable use cases where SPIFFE-aware and non-SPIFFE-aware clients are consuming the same JWKS endpoint.

I am adding this issue as an agenda item for next SIG-Spec call
