### ISSUE TITLE
Re-organize this repo

### ISSUE THREAD

**Issue by evan2645** [spiffe/spiffe#2]
- [x] 1. Top-level doc explaining what SPIFFE is. This document should link to all the following
- [x] 1. Core SPIFFE RFC
- [x] 1. X.509 SVID RFC
- [x] 1. SPIFFE Community Information
- [x] 1. svid-test

**Comment by y2bishop2y** [comment]
How are we going to document the WL API? We moved all the docs to the NodeAgent. Should we just create a README.md that points to that proto buffer ?

**Comment by evan2645** [comment]
@y2bishop2y I am thinking that we can create a similar standards doc which outlines those endpoints, their parameters, and their return format. I can link to the protobuf from there....

I realize that it duplicates the API signature to do this, however I think it's important, especially considering some implementors may not be familiar with/understand protobuf definition. I think IETF has got a standardized way to express these things... I will look into it

**Comment by evan2645** [comment]
All done via #12 and #18
