### ISSUE TITLE
Apple ARM Support - Mac OS

### ISSUE THREAD

**Issue by wibarre** [spiffe/spiffe#213]
Mac OS - X quick start throws error when starting the agent. ARM is not supported. 
ERRO[0000] failure getting variant            error="getCPUInfo for OS darwin: not implemented"

From Andrew H.
We have an indirect dependency on containerd, which is doing this check during process init, unrelated to anything we use it for. We support macOS so we should look into fixing this, if possible.

**Comment by azdagron** [comment]
Thanks for opening this @wibarre! However, this repository is for tracking issues against the spiffe specification. Would you mind opening an issue against the SPIRE repository? https://github.com/spiffe/spire/issues.
