### ISSUE TITLE
Allow Other non-SPIFFE ID URI SANs

### ISSUE THREAD

**Issue by andrewpmartinez** [spiffe/spiffe#219]
>An X.509 SVID MUST contain exactly one URI SAN, and by extension, exactly one SPIFFE ID. SVIDs containing more than one SPIFFE ID introduce challenges related to auditing and authorization logic, and SVIDs containing more than one URI SAN introduce challenges related to SPIFFE ID validation

The only challenge I can see introduced by allowing other non-SPIFFE ID URI SANs would be that auditing and authorizing logic would have to loop over the URI sans and look for multiple `spiffe://` URI SANs. If multiple SPIFFE IDs are found the SVID can be rejected.

That seems like a small price to pay when weighed against the reduced interoperability it introduces by commandeering all URI SANs.

**Comment by spikecurtis** [comment]
@andrewpmartinez is there a particular URI SAN application or use case you're interested in?  Part of the calculus in this trade-off is around the practical impact, so I'd love to hear more about what you're wanting to do.

**Comment by andrewpmartinez** [comment]
I'm working with a system that I was considering implementing the SPIFFE spec in, but we have already existing clients and systems. If we transitioned in this direction there would be a period of time where SPIFFE and non-SPIFFEcertificates would exist. They can be the same certificate if multiple URI sans can be declared. In addition, the data in the URIs defined previously has to move to another SAN for the long term.

However, SAN formats are pretty static so we are looking at an extension of some sort or squeezing into another SAN.

It isn't a great situation.

**Comment by spikecurtis** [comment]
So, I understand from your comment that you are currently using a URI SAN.  Would it be possible for you to describe what specifically the URI SAN is being used for?  Is it also workload identity, or some other kind of data?

**Comment by andrewpmartinez** [comment]
It is claims data, much like how a JWT can have the standard claims as well as private claims.

Sometimes these claims are temporary elevations of privilege that aren't statically configured in a decentralized system. In larger deployments synchronizing claim data is not feasible at scale.

**Comment by spikecurtis** [comment]
We discussed this on a recent SIG-spec call, and we do still feel that while the extra validation complexity may seem incrementally small, we are concerned about increments adding up.

There is an additional concern regarding compatibility with existing validators. Many validators ensure that the number of URI SANs == 1 and take uriSAN[0].

That said, we're definitely open to a case being made by the community that it's worth the difficulties to make a change like this.  The SPIFFE Slack and SIG-spec calls are open to all and we'd love to see you there.

**Comment by andrewpmartinez** [comment]
Thanks for the time you've invested in this. I've joined the relevant Google Groups and Slack+channels. I don't know how I might contribute, but I'm interested in joining the SIG meetings.

> There is an additional concern regarding compatibility with existing validators. Many validators ensure that the number of URI SANs == 1 and take uriSAN[0].

Library friction is an understandable concern and would be enough for me in your position to resist changing the spec. In addition, I'm just one voice. Maybe at a later date, others will join me, or not!

I would say, if there is ever a time when the spec has a major-enough version change, maybe this area can be revisited. Altering the spec to specifically state that the SPIFFE ID is only in `uriSAN[0]` is also amenable. Right now IIRC that can be inferred, but it could be strongly stated in the future. Index `[0]` should be deterministic as the DER format is ordered. Hence, additional URI SANs wouldn't matter.
