### ISSUE TITLE
X509-SVID with a CA/B Forum EV Certificate 

### ISSUE THREAD

**Issue by ghaidinyak** [spiffe/spiffe#233]
Does anyone know how to create a X509-SVID certificate using a CA/B Forum EV Certificate? I don't believe that CA/B Forum members support SAN URI fields, just verified DNS & IP address SAN entries.

**Comment by evan2645** [comment]
> I don't believe that CA/B Forum members support SAN URI fields, just verified DNS & IP address SAN entries.

This is correct. SPIFFE auth is different than web PKI - they can be mixed and matched in many circumstances, but not this one.
