### ISSUE TITLE
Bring CLOMonitor Score to 100%

### ISSUE THREAD

**Issue by alinskens** [spiffe/spiffe#234]
This repo is signed up as part of the KubeCon [Security Slam](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/experiences/#security-slam). I'm bringing to your attention the checklist from the official [CLOMonitor page for SPIFFE](https://clomonitor.io/projects/cncf/spiffe) -- it refreshes every hour, so it should be up-to-date.

### Summary

**Repository**: spiffe
**URL**: https://github.com/spiffe/spiffe
**Checks sets**:  `COMMUNITY` + `CODE`
**Score**: 57

### Checks passed per category

| Category  |  Score  |
| :----------------- | --------: |
|  Documentation  |  90%  |
|  License  |  75%  |
|  Best Practices  |  15%  |
|  Security  |  45%  |
|  Legal  |  0%  |

### Documentation [90%]

  - [ ] Adopters ([_docs_](https://clomonitor.io/docs/topics/checks/#adopters))
  - [ ] Changelog ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [x] [Code of conduct](https://github.com/spiffe/spiffe/blob/main/CODE-OF-CONDUCT.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#code_of_conduct))
  - [x] [Contributing](https://github.com/spiffe/spiffe/blob/main/CONTRIBUTING.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [x] [Governance](https://github.com/spiffe/spiffe/blob/main/GOVERNANCE.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#governance))
  - [x] [Maintainers](https://github.com/spiffe/spiffe/blob/main/CODEOWNERS) ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/spiffe/spiffe/blob/main/README.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  - [ ] Roadmap ([_docs_](https://clomonitor.io/docs/topics/checks/#roadmap))
  - [x] [Website](http://spiffe.io) ([_docs_](https://clomonitor.io/docs/topics/checks/#website))
  
### License [75%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#license_spdx_id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#license_approved))
  - [ ] License scanning ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))
  
### Best Practices [15%]

  - [x] Analytics ([_docs_](https://clomonitor.io/docs/topics/checks/#analytics))
  - [ ] Artifact Hub badge ([_docs_](https://clomonitor.io/docs/topics/checks/#artifacthub_badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#cla)) `EXEMPT`
  - [ ] Community meeting ([_docs_](https://clomonitor.io/docs/topics/checks/#community_meeting))
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#dco))
  - [ ] Github discussions ([_docs_](https://clomonitor.io/docs/topics/checks/#github_discussions))
  - [ ] OpenSSF badge ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf_badge))
  - [ ] Recent release ([_docs_](https://clomonitor.io/docs/topics/checks/#recent_release))
  - [ ] Slack precense ([_docs_](https://clomonitor.io/docs/topics/checks/#slack_presence))
  
### Security [45%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary_artifacts))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code_review))
  - [x] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous_workflow))
  - [ ] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency_update_tool))
  - [ ] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained))
  - [ ] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#sbom))
  - [ ] Security policy ([_docs_](https://clomonitor.io/docs/topics/checks/#security_policy))
  - [ ] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed_releases))
  - [x] Token permissions ([_docs_](https://clomonitor.io/docs/topics/checks/#token_permissions))
  
### Legal [0%]

  - [ ] Trademark disclaimer ([_docs_](https://clomonitor.io/docs/topics/checks/#trademark_disclaimer))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).

**Comment by evan2645** [comment]
Thanks for opening this. I've taken a look at the list and there are many things there that don't apply to this repo. I think we have all of the important stuff in place - if there's something specific you'd like to see added, a new issue and/or pr would be helpful 🙏
