### ISSUE TITLE
2023 H1 SSC Election

### ISSUE THREAD

**Issue by dfeldman** [spiffe/spiffe#244]
### **2023 H1 SSC Election**
This is the official tracking issue for the 2023 H1 SSC election. The timeline for this election is as follows:

APRIL 5, 2023: Nominations open
APRIL 12, 2023: Nominations close
APRIL 25, 2023: Polls open
MAY 1,  2023: Polls close and results announced
MAY 3, 2023: New term starts

**How to Participate**
All SPIFFE community members and contributors demonstrating active engagement in the project(s) are invited to both nominate and vote on new SSC members. The eligible participants are listed below. For more information about the definition of active engagement, and how this list was compiled, please see the Election and Term Mechanics section of the [SSC Charter](https://github.com/spiffe/spiffe/blob/master/ssc/CHARTER.md#election-and-term-mechanics).

All eligible participants MUST have an email address publicly associated with their GitHub account. You may be omitted from the participant list if we're unable to determine your email address.

If you are an active SPIFFE community member or contributor but are not included in the list below, please contact the SSC at [ssc-elections@spiffe.io](mailto:ssc-elections@spiffe.io) and cc Daniel Feldman, [dfeldman.mn@gmail.com](mailto:dfeldman.mn@gmail.com) and we will be happy to include you.

You can also reach the SSC using the #ssc channel on SPIFFE Slack.

**Nominating an SSC Member**
Eligible participants may nominate up to two candidates per available SSC seat during the nomination period. They may nominate themselves or someone else.

If you'd like to nominate an SSC member for this election cycle, please follow these steps:

Verify that your GitHub handle is included in the list of eligible participants below
Verify that, in your best judgement, the nominee meets the criteria specified in the Nominee Qualifications section of the [SSC Charter](https://github.com/spiffe/spiffe/blob/master/ssc/CHARTER.md#nominee-qualification)
Fork this repository
Copy ssc/elections/NOMINEE_TEMPLATE.md into the appropriate subdirectory, and name it after the person to be nominated
For example, from the root directory:
$ cp ssc/elections/NOMINEE_TEMPLATE.md ssc/elections/2021H1/JANE_DOE.md
Fill in all fields in the copied template as completely as possible
Open a GitHub Pull Request back to this repository to add the new nominee
Create a new commit with the name of the election and nominee
For example, Nominate Jane Doe for 2021H1 SSC Election
Open a new GitHub Pull Request against https://github.com/spiffe/spiffe
Give the Pull Request the same name as the commit it includes
An SSC member will review the nomination and merge it when ready

**Electing an SSC Member**
The SPIFFE project uses the [CIVS](https://civs.cs.cornell.edu/) tool to conduct its elections. Once the polls open, all eligible participants will receive an email from this tool. The email includes a link which can be used to vote. Do not share this link, as it is private.

If you are in the list of eligible participants, and you don't receive a link on the day the polls open, please contact the SSC at [ssc-elections@spiffe.io](mailto:ssc-elections@spiffe.io).

Each participant casts a single ranked vote. If more than one SSC seat is available, the top N nominees will be selected.

**Eligible Participants**
This section lists everyone eligible to participate in this SSC election cycle. If you believe you were omitted in error, please contact the SSC at [ssc-elections@spiffe.io](mailto:ssc-elections@spiffe.io) and cc Daniel Feldman. Or, reply to this issue.

-  (@Abirdcfly) <fp544037857@gmail.com>
- Aura (@Aura6) <aura1391215@gmail.com>
- Basavaraju Girriamma (@Basavaraju-G) <bgirriam@redhat.com>
- Josh Harris (@Celant) <joshuaharris51@gmail.com>
- Furkan Türkal (@Dentrax) <furkan.turkal@hotmail.com>
- Dmitry Kartsev (@Dimss) <dmitry.kartsev@cnvrg.io>
- Benjamin Krämer (@Falco20019) <benjamin.kraemer@alien-scripts.de>
- Falko (@HaBaLeS) <falko@lehmann-carpzov.de>
- Hirad Rasoolinejad (@Hiiirad) <hirad.rad@gmail.com>
- Josh van Leeuwen (@JoshVanL) <me@joshvanl.dev>
- Kaizhe Huang (@Kaizhe) <derek0405@gmail.com>
- Marcos Yacob (@MarcosDY) <marcos.yacob@hpe.com>
-  (@Ruoyu-y) <ruoyu.ying@intel.com>
- Anton Kaymakchi (@StupidScience) <tonysignal@gmail.com>
- Tony Jarriault (@TJarriault) <tony.jarriault@capgemini.com>
- Abe Sharp (@abe-hpe) <abe@hpe.com>
- Alexander Viktorov (@alexviktorov) <a.viktorov@live.com>
- Andrew Harding (@azdagron) <azdagron@gmail.com>
- Bendik Paulsrud (@bendikp) <bendik.paulsrud@statnett.no>
- Bryon Nevis (@bnevis-i) <bryon.nevis@intel.com>
- Brandon Menc (@brandonmenc) <brandonmenc@icloud.com>
- Sascha Brawer (@brawer) <sascha@brawer.ch>
- Cole Kennedy (@colek42) <colek42@gmail.com>
- Daniela Cortes Antonio (@dcortesantonio) <dcortesantonio@gmail.com>
- Batuhan Apaydın (@developer-guy) <developerguyn@gmail.com>
- Donald Hunter (@donaldh) <donhunte@redhat.com>
- Eli Nesterov (@elinesterov) <github@nesterov.us>
- Erik Godding Boye (@erikgb) <egboye@gmail.com>
- Evan Gilman (@evan2645) <evan2645@gmail.com>
- Faisal Memon (@faisal-memon) <fymemon@yahoo.com>
- Frederick F. Kautz IV (@fkautz) <fkautz@pseudocode.cc>
- Vincent (@fleeto) <dustise@live.com>
- Frank (@frankli0324) <frankli0324@hotmail.com>
- Guilherme Carvalho (@guilhermocc) <guilhermocc@proton.me>
- tomsawyer (@itomsawyer) <tomsawyer126@gmail.com>
- Jesse Sanford (@jessesanford) <jessesanford@gmail.com>
- Keegan Witt (@keeganwitt) <keeganwitt@gmail.com>
- Igor Baliuk (@lodthe) <baliuk.igor@gmail.com>
- M1a0 (@loveyana) <liyuhan.loveyana@bytedance.com>
- Max Lambrecht (@maxlambrecht) <maxlambrecht@gmail.com>
- Maximiliano Churichi (@mchurichi) <mchurichi@gmail.com>
- Farasath Ahamed (@mefarazath) <farasatha@wso2.com>
- Maartje Eyskens (@meyskens) <maartje@eyskens.me>
- Zhou Ting (@moting9) <moting9@hotmail.com>
- Mariusz Sabath (@mrsabath) <mrsabath@gmail.com>
- Patrick Liao (@patricka3125) <liao.patrick@gmail.com>
- Pete Cable (@petercable) <petercable@gmail.com>
- Rodrigo Lopes (@rodrigolc) <rodrigolpscarvalho@gmail.com>
- Saylor Berman (@sjberman) <s.berman@f5.com>
-  (@swamibluedata) <swami.viswanathan@hpe.com>
- 天马行空 (@tanjunchen) <tanjunchen20@gmail.com>
- John (@thejohnrichard) <john.ramacher@transferwise.com>
- Uchechukwu Obasi (@thisisobate) <obasiuche62@gmail.com>
- Thomas Richner (@thomasrichner-oviva) <thomas.richner@oviva.com>
- William Barrera (@wibarre) <wibarre@gmail.com>
- Willian Alves (@willallves) <wiilliian.alves@gmail.com>
- Zhan Jiang (@zeromath) <zinzoeng@gmail.com>
- Zachary M. Train (@zmt) <no1@zmt.org>

**Eligible Participants with Missing Email Addresses**
The following participants would normally be eligible to participate, but do not have email addresses published on their GitHub account. Please publish an email address and contact the SSC at [ssc-elections@spiffe.io](mailto:ssc-elections@spiffe.io) and cc Daniel Feldman [dfeldman.mn@gmail.com](mailto:dfeldman.mn@gmail.com) to be added to the list of eligible participants. 

- @IvMdlc
- @Kathiresan-durairaj
- @LaithLite
- @Murphy-hub
- @PhilCorney
- @ajessup
- @alexandrealvino
- @alexdotsh
- @alinskens
- @alitta-german
- @amartinezfayo
- @amitlicht
- @amoore877
- @andrewpmartinez
- @anvega
- @bbeuning
- @bendu
- @bengrissinger
- @bri365
- @c4rlo
- @chdalski
- @cooper190113
- @danieled-it
- @deanyxu
- @denis-tingaikin
- @dennisgove
- @divaspathak
- @egkelly
- @georgevanburgh
- @georgi-lozev
- @ghaidinyak
- @glazychev-art
- @goergch
- @hiyosi
- @idexter
- @inajob
- @jaellio
- @jcrumb-u21
- @jiashuChen
- @joshuastern
- @kfox1111
- @ldez
- @lucaserafini-dev
- @maia-iyer
- @mamy-CS
- @manasmishra
- @marcofranssen
- @mattbates
- @mmorel-35
- @moe-omar
- @n-th
- @naveensrinivasan
- @nickperry
- @noxora
- @nstott
- @nweedon-u
- @pbhalera
- @peterj
- @pranay-k12
- @prasadborole1
- @pxp928
- @radnair
- @raffaelespazzoli
- @rgl
- @ricfeatherstone
- @richardstone
- @rturner3
- @ryysud
- @sanderson042
- @segator
- @shashankram
- @skiptomyliu
- @slimHawaiian
- @snovo
- @sorindumitru
- @spikecurtis
- @srago
- @stevend-uber
- @sudeeptoroy
- @sys0613
- @szvincze
- @troydai
- @vellimani-pixel
- @vish-k
- @wolfchimneyrock
- @yangmarcyang
- @yueqiao1

**Comment by amoore877** [comment]
FYI we'll be extending nominations another week, and just to be clear the folder to put nominations in is `ssc/elections/2023H1`.

**Comment by Falco20019** [comment]
I think the first steps of https://github.com/spiffe/spiffe/tree/main/ssc/elections#t-28-days-nomination-opens are still missing, as there doesn't seem to be `ssc/elections/2023H1` yet (and I don't see the PR).
