### ISSUE TITLE
Clarify why the SVID signing certs "MUST NOT set the `pathLenConstraint` field"

### ISSUE THREAD

**Issue by briansmith** [spiffe/spiffe#25]
In particular, `pathLenConstraint` set to 0 would mean that the SVID signing cert is valid for signing leaf certs only and can't be used to cross-sign other SVID signing certs (for other trust domains). This seems like a valid restriction to want to place on a SVID signing certificate so either (a) `pathLenConstraint` should be allowed, or (b) the spec should explain *why* path length constraints aren't allowed.

**Comment by evan2645** [comment]
I had wondered about this too when writing the doc. That requirement was copy-pasted from the original SVID spec. Looking at Git history, that language came in w/ the initial commit and was sourced from an unlinked Google doc. Perhaps @ajessup can shed some light on the reasoning here?

There is a use case in which SPIFFE signing authorities may be chained together, and I suspect that this language came from a desire to support that use case, though it does seem fairly heavy handed. As an operator, I would like to set `pathLenConstraint` to `0` on signing authorities that I know I won't be chaining, or if chaining is not part of my SPIFFE implementation/deployment pattern.

**Comment by Preskton** [comment]
I'm new to SPIFFE, but interested in this as well, especially as it relates to integrated into an existing PKI hierarchy.  Since signing cert must be issued with a "CA" type, it seems this would preclude someone from using a PKI where higher order CAs apply a path length constraint.

**Comment by evan2645** [comment]
@Preskton yes it would be problematic in the event that the user would like higher order CAs to be SPIFFE-compliant (this is not a requirement at the moment).

Since some time has gone by and we still haven't heard any good reasons for keeping it, I propose we strike the requirement from the spec. Would you like to raise a PR where we can discuss this further?

**Comment by evan2645** [comment]
#52 has been merged, which specifies pathLenConstraint as optional. Marking this issue as resolved. Thanks very much @briansmith and @Preskton!
