### ISSUE TITLE
2023H2 SSC Election

### ISSUE THREAD

**Issue by dfeldman** [spiffe/spiffe#258]
### 2023 H2 SSC Election
This is the official tracking issue for the 2023H2 SSC election. The timeline for this election is as follows:
* AUGUST 23, 2023: Nominations open
* SEPTEMBER 6, 2023: Nominations close
* SEPTEMBER 13, 2023: Polls open
* OCTOBER 11, 2023: Polls close
* NOVEMBER 1, 2023: Results announced

### How to Participate
All SPIFFE community members and contributors demonstrating active engagement in the project(s) are invited to both nominate and vote on new SSC members. An initial batch of eligible participants discovered via automation is listed below. **However, if you are not on the list below, but you participate in the project, you are still eligible to be nominated and to vote.**

For more information about the definition of active engagement, and how this list was compiled, please see the Election and Term Mechanics section of the [SSC Charter](https://github.com/spiffe/spiffe/blob/master/ssc/CHARTER.md#election-and-term-mechanics).

If you feel that you are an active SPIFFE community member or contributor but are not included in the list below, please contact the SSC at [ssc-elections@spiffe.io](mailto:ssc-elections@spiffe.io) and cc [dfeldman.mn@gmail.com](mailto:dfeldman.mn@gmail.com) and we will be happy to include you. Even if you do not interact with GitHub normally, to be an election candidate a GitHub account is required as this is how SSC members gain administrative rights on the SPIFFE projects.

### Nominating an SSC Member
Eligible participants may nominate up to two candidates per available SSC seat during the nomination period. They may nominate themselves or someone else.

If you'd like to nominate an SSC member for this election cycle, please follow these steps:

Verify that your GitHub handle is included in the list of eligible participants below
Verify that, in your best judgement, the nominee meets the criteria specified in the Nominee Qualifications section of the [SSC Charter](https://github.com/spiffe/spiffe/blob/master/ssc/CHARTER.md#nominee-qualification)
Fork this repository
Copy ssc/elections/NOMINEE_TEMPLATE.md into the appropriate subdirectory, and name it after the person to be nominated
For example, from the root directory:
$ cp ssc/elections/NOMINEE_TEMPLATE.md ssc/elections/2021H1/JANE_DOE.md
Fill in all fields in the copied template as completely as possible
Open a GitHub Pull Request back to this repository to add the new nominee
Create a new commit with the name of the election and nominee
For example, Nominate Jane Doe for 2023H2 SSC Election
Open a new GitHub Pull Request against https://github.com/spiffe/spiffe
Give the Pull Request the same name as the commit it includes
An SSC member will review the nomination and merge it when ready

### Electing an SSC Member
The SPIFFE project uses the [CIVS](https://civs.cs.cornell.edu/) tool to conduct its elections. Once the polls open, all eligible participants will receive an email from this tool. The email includes a link which can be used to vote. Do not share this link, as it is private.

If you are in the list of eligible participants, and you don't receive a link on the day the polls open, please contact the SSC at [ssc-elections@spiffe.io](mailto:ssc-elections@spiffe.io).

Each participant casts a single ranked vote. If more than one SSC seat is available, the top N nominees will be selected.

### Voter list (collected from GitHub activity)
Note: If you have a public email address associated with your GitHub account, we will email you with a reminder to vote. However, most GitHub accounts do not have a public email address. 

Abirdcfly
Basavaraju-G
CathPag
ChaosInTheCRD
Dentrax
Dimss
EItanya
FedeNQ
Hiiirad
IvMdlc
JU4N98
LaithLite
MarcosDY
Murphy-hub
Neniel
PetrMc
PhilCorney
RiichardCC
Ruoyu-y
SQUIDwarrior
StupidScience
TJarriault
TnGadaria
Ve33y
Zilosz
abe-hpe
achaurasiaConfluent
ajessup
akaloti
alexandrealvino
alexviktorov
alinskens
amartinezfayo
amoore877
anvega
azdagron
bbeuning
bellycat77
bendikp
bleggett
bnevis-i
bobo333
bortek
bramaq
brandonmenc
brawer
bri365
c4rlo
cccsss01
chainguard-alerter
chenxi-neo
chiragk25
cooper190113
d-goro
danieled-it
datosh
dennisgove
dependabot[bot]
developer-guy
dfeldman
dherbrich
divaspathak
doffi88
drewwells
edwbuck
egkelly
elinesterov
enj
erikgb
evan2645
faisal-memon
fdeantoni
fkautz
fleeto
frankli0324
ghaidinyak
grameshtwilio
guilhermocc
gurfm
hellerda
hiyosi
huang195
hugordon7
idexter
inajob
itomsawyer
jaellio
jcrumb-u21
jessesanford
joshuastern
kabhiibm
keeganwitt
kfox1111
knabben
kongweiguo
krishnakv
ldez
lodthe
loveyana
maia-iyer
mamy-CS
manasmishra
marcofranssen
mattbates
mattchapleau
matthewdevenny
maxlambrecht
mchurichi
meyskens
mmaymann
mmorel-35
moe-omar
morrowc
moting9
mrsabath
nickperry
nicolaenicora
nstott
nweedon-u
onesafe
petercable
peterj
pranay-k12
prasadborole1
pxp928
radnair
raffaelespazzoli
ramonssarmento
ricfeatherstone
richnwilson
rkaippully
rodrigolc
rturner3
rushi47
ryysud
sanderson042
sarroutbi
sebastianGit
segator
shashankram
sjberman
slimHawaiian
snovo
sorindumitru
stevend-uber
sudeeptoroy
sumantfordev
swamibluedata
szvincze
tanjunchen
thejohnrichard
thisisobate
thomasrichner-oviva
tihhoni
timbuchwaldt
troydai
udf2457
unnathik
v0lkan
vellimani-pixel
vish-k
vivekvamsi-VV
voltagex
willallves
zmt

**Comment by elinesterov** [comment]
I would suggest extending `SEPTEMBER 6, 2023: Nominations close` or shifting everything to after Labor day weekend otherwise we could find ourselves in the same situation as last elections because of the time conflict with KubCon.

**Comment by amoore877** [comment]
We are extending `Nominations close` to September 11th, 2023.

**Comment by WanderingStar** [comment]
I found the descriptions here helpful in casting my vote: https://github.com/spiffe/spiffe/tree/main/ssc/elections/2023H2

**Comment by evan2645** [comment]
I think this election is over, should we close the issue?

**Comment by amoore877** [comment]
> I think this election is over, should we close the issue?

Agreed, though we also need to update https://github.com/spiffe/spiffe/tree/main/ssc with results
