### ISSUE TITLE
Repo for k8s-spiffe-workload-jwt-exec-auth

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spiffe#299]
I have a tiny project I'd like to contribute called k8s-spiffe-workload-jwt-exec-auth.

It is a kubernetes auth plugin that uses the spiffe workload api to get a jwt token. Using it, any kubernetes client using workload can use spiffe for automatic authentication to the kube-apiserver.

**Comment by amoore877** [comment]
Just to follow https://github.com/spiffe/spiffe/blob/main/NEW_PROJECTS.md -

Who will initial maintainers be? Is there a long roadmap for this project, and if so can you rough it out?
Lots more potential questions in that doc to be answered.

Though I know from our slack discussions this will largely be N/A or very brief, we also are wanting to dogfood the NEW_PROJECTS process :)

And just to quote from the process itself- `It's ok if there's not fully fleshed-out answers to each of these,`

**Comment by kfox1111** [comment]
Its a tiny project, so, ssc. but I'd be an initial maintainer.

The code is basically done now. So, no long roadmap. The code is 51 lines of golang.

**Comment by kfox1111** [comment]
Closing as the repo was created.
