### ISSUE TITLE
Tiny Project: k8s-spiffe-workload-auth-config

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spiffe#306]
In trying to better integrate k8s-spiffe-workload-jwt-exec-auth with Kubernetes we have run into a configuration problem.

The Kubernetes API Server needs to fetch the JWT CAs from SPIRE in order to validate tokens and needs to be able to update them as needed.

The seemingly obvious choice would be to use the spiffe-oidc-discovery-provider. Unfortunately, the API Server only supports validated HTTPS for OIDC discovery, so it needs a non SPIRE CA in order to secure the fetching of SPIRE JWT CA's. This is not a very good solution when public CA's are unavailable or using SPIRE as the bottom turtle is required.

The Kubernetes AuthenticationConfiguration object that is on disk supports the jwt[].issuer.certificateAuthority property that can be used to set the current CA's, and the file will be re-read into the API Server if it changes.

So, the proposed tool will run as a service, fetch the x509 CAs via SPIFFE Workload API, and update the jwt[].issuer.certificateAuthority property as needed to inform Kubernetes as to the proper CAs to allow access to the SPIRE secured spiffe-discovery-provider.

It should be ~100 lines of golang and very static once completed, so it fits the Tiny Project definition.

**Comment by amoore877** [comment]
Strong yet simple support to enable other orgs to begin using SPIRE as the turtle underneath k8s, and maybe my org can remove its related custom work for the same :)

I like it. Let's leave this open for a reasonable comment period in case there are questions or concerns.

**Comment by kfox1111** [comment]
This was setup. Closing the issue.
