### ISSUE TITLE
Project Proposal: SPIFFE AWS Credential Helper

### ISSUE THREAD

**Issue by strideynet** [spiffe/spiffe#307]
Addressed @v0lkan 's comments on https://github.com/spiffe/spiffe/issues/301

---

## Initial Maintainer List

- Noah Stride (Teleport) - [@strideynet](https://github.com/strideynet)  
    If we need further maintainers, I can draw from other members of my team here at Teleport. I was hoping this could fall under the umbrella of the "tiny projects" maintainer group.

## Purpose

- What specific pain point does the project address?
    - Using the Workload API and SPIFFE SVIDs to authenticate to AWS - initially focussed on X509 SVIDs and the AWS RolesAnywhere API.
- What does "done" mean for the project? What is the idealized vision for the shape of the project? What are the milestones to complete for each level of [maturity](https://github.com/spiffe/spiffe/blob/main/MATURITY.md)?
    - This project is likely to be quite small and is tightly scoped. Ideally, core functionalitywould be complete within a few weeks and from that point onwards, focus would be on keeping on top of dependency updates/CVEs etc.
- What are the current workarounds or alternative solutions, and why are they inadequate?
    - Regularly invoking spiffe-helper separately to rolesanywhere-credential-helper
        - This works today, and is acceptable in Linux environments with an init system where spiffe-helper can run as a distinct service.
        - This architecture is not well-suited for containerised environments where an init system is not available.
    - Alternative: Using spiffe-helper wrapped around rolesanywhere-credential-helper
        - Problems with spiffe-helper
            - Today, it is not well designed for acting as a "wrapper" around a short-lived binary. For this use-case, it would be ideal if spiffe-helper exited after the underlying command had been executed.
            - Today, it does not support selecting an SVID based on the
            - It is not clear what guarantees are made in regard to the STDOUT of spiffe-helper, if a change is introduced which emits log messages over STDOUT, this will break the credential helper's functionality.
        - Problems with rolesanywhere-credential-helper
            - Pre-built binaries are linked to glibc
            - Pre-built binaries are not available for a wide range of common architectures
    - Alternative: adding AWS Roles Anywhere support directly into spiffe-helper
        - Increases the upstream dependencies of spiffe-helper
    - Alternative: adding SPIFFE support into the rolesanywhere-credential-helper
        - Dependent on AWS accepting this contribution.
        - Dependent on AWS to accept further contributions to improve UX in future or to patch issues.
        - Today, several existing issues with rolesanywhere-credential-helper already make it awkward to use (e.g pre-built binaries are linked to glibc and unavailable for common architectures)
- How does your project align with SPIFFE's overall mission and goals?
    - Eases adoption/reduces barrier to entry of SPIFFE by organisations who wish to use SPIFFE to authenticate to AWS APIs.
    - Acts as "proof" that SPIFFE interoperates with other platforms/demonstrates potential use-cases - encouraging organisations to consider adopting SPIFFE.
    - Authenticating with AWS seems a common-enough use-case that this is valuable enough to fall under the SPIFFE umbrella.
- Who are the primary end-users or beneficiaries of this project?
    - Organizations who wish to use SPIFFE to authenticate to AWS APIs, typically from workloads not hosted in AWS. This is likely to align with larger enterprises who have a hybrid cloud/heterogenous strategy for infrastructure - it's generally less common to see smaller organisations leveraging multiple clouds.

## Direction

- What is the project’s roadmap for the next 6-12 months?
    - MVP: Working authentication to AWS APIs using AWS Roles Anywhere and a SPIFFE Workload API endpoint.
    - Future improvements:
        - Ability to specify which X509 SVID should be selected based on a hint.
        - Upstreaming improvements to the rolesanywhere-credential-helper library to this binary
        - E2E testing to assert that this implementation and AWS continues to be compatible with SPIFFE for authentication. This would involve a nightly/PR CI job using the tool to authenticate with an AWS project (managed with Tofu) using SPIFFE credentials and perform a simple action against the AWS API (e.g read from an S3 bucket).
- What are practices or styles that will be encouraged or discouraged?
    - Standard Go best practices, testing etc.
- How will the project scale? What are the scalability goals?
    - I do not expect the project to "scale", it's fairly tightly scoped.
- Are there any legal or ethical considerations?
    - Use of AWS product name
    - Use of AWS library
        - Licensed under Apache License 2.0 - so I expect this to be a non-problem.
- What are potential challenges, and how do you plan to overcome them?
    - Keeping up with upstream changes introduced in the library published by AWS
        - History seems to indicate that they do not often make changes to this API or to the library itself. A small group of maintainers should be able to stay on top of this.
        - It seems like it would be appropriate to establish a channel within the spiffe-slack and to subscribe this to notification of changes to the upstream AWS project as well as announcements in regards to the RolesAnywhere API.
- What kind of community involvement do you foresee (e.g., are there opportunities for novice contributors, or is the project more suitable for experts in the field?)
    - To be honest, I expect the project to be "done" within a fairly short amount of time and then to enter a period of maintenance.
    - Novice contributors would be welcomed to involve themselves with bug fixes, documentation changes, examples etc - and I'd be happy to support them in this.
- What technologies will the project leverage, and are they aligned with the larger ecosystem?
    - Go
        - Aligned with most SPIFFE and CNCF projects
- How will the project maintain data integrity, security, and privacy?
    - Sensitive information will not be included in logs.
    - Project will use automated tooling (e.g dependabot) to keep on top of dependency updates
    - Project will include a test suite to verify functionality.
- Are there any possible collaborations with existing SPIFFE projects?
    - This project could lead to upstream changes in the spiffe-go SDK
- How will your project deal with failure scenarios or fallbacks?
    - One primary risk will be the AWS API changing in a breaking way or an upstream package breaking. We will monitor this through the E2E testing suite.
    - Another potential failure scenario would be a vulnerability within an upstream package, monitoring for CVEs announced in dependencies will be used to track this.

## Governance

- How will maintainers be added or removed? What is the goal number of maintainers?
    - The goal would be to have 2-3 maintainers. The project is fairly simple. Ideally, the project would fall under the "tiny project" maintainers group which I'd be happy to join.
- How often will the maintainers meet?
    - Synchronous meetings seem unnecessary for a project of this size.
- How will maintainers interact with contributors and review their Pull Requests and Issues? Slack? Dedicated online meetings? What is the goal turn around time?
    - Interaction within GitHub Issues and Pull Requests and Slack seems sufficient.
    - Target to respond to tickets within 1 week.
    - Target to respond to security-sensitive issues within 2 working days.
- What conflict resolution mechnisms will the maintainers follow? (e.g., allocated debate time? Majority vote? Unanimous vote for certain topics? What is the SLO for resolution?)
    - Conflict resolution will be via escalation to the SPIFFE SSC.

## Similar Projects

- Do similar projects already exist actively within the SPIFFE community? If so, what makes this project sufficiently unique to justify any overlap?
    - Whilst this functionality could be built into spiffe-helper, I'm concerned that it would bloat it's currently fairly tightly-scoped purpose and implementation. We will include a statement on the scope of the project within the readme to guide direction - and link to spiffe-helper as a more generalised tool that may be suitable for other purposes.
- Do similar projects exist outside of SPIFFE that can better help us understand the project's value?
    - N/A
- Has this project existed in the past but was abandoned or closed out? What is different in today's world?
    - As far as I am aware, no.

**Comment by strideynet** [comment]
I see we had https://github.com/spiffe/spiffe/pull/294 for raising PRs for proposals instead - more than happy to raise this as PR. Might make addressing feedback a little easier.

**Comment by kfox1111** [comment]
I'm in favor of this. I think the tiny projects could benefit from some common infrastructure too (ex: github actions for testing, builds, releases, etc), so would be happy to help with that.

**Comment by amoore877** [comment]
Thanks for your patience. There's been support and no objections so I think we are good to go here. Please sit tight for a little bit longer for creation.

**Comment by amoore877** [comment]
Forgot to add- speaking for myself and not unilaterally as SSC, I would definitely support similar work for interacting with GCP, Azure, OCI, etc.

**Comment by strideynet** [comment]
> Forgot to add- speaking for myself and not unilaterally as SSC, I would definitely support similar work for interacting with GCP, Azure, OCI, etc.

Definitely agreed - I think for the most part, we're fortunate in that most of these other applications tend to work pretty natively without some kind of credential helper (at least with JWT SVIDs) - it's AWS Roles Anywhere that's particularly awkward in this regard.

Although, I do wonder if there's some things we could do with `spiffe-helper` to it integrate a little better for these other platforms - or at least provide some use-case specific documentation. Most of these other platforms seem to happily accept a process they should invoke to fetch a JWT, and will read it back from STDOUT. Does `spiffe-helper` have a mode today where it just writes a JWT-SVID to stdout ? If not, that could be a relatively low-hanging fruit to enable those use-cases.

Regardless, I am in the midst of writing documentation re: Teleport Workload Identity and AWS, GCP and Azure. If I'm lucky, I may be able to carve out some time to contribute some of this information back to the SPIFFE documentation - if not in full guide format, then at least with some pointers towards the appropriate documentation on said platforms and any SPIFFE specific advice.

**Comment by kfox1111** [comment]
https://github.com/spiffe/aws-spiffe-workload-helper has been created and you should have access to it.

When you have a README.md ready, please add the dev header like in https://github.com/spiffe/k8s-spiffe-workload-jwt-exec-auth/blob/main/README.md for a while.

**Comment by kfox1111** [comment]
This was setup. Closing the issue.
