### ISSUE TITLE
Repo Request for vsecm-sdk-go, vsecm-sdk-rust

### ISSUE THREAD

**Issue by v0lkan** [spiffe/spiffe#308]
This is a tiny project request for [VMware Secrets Manager](https://vsecm.com/) (VSecM) Golang SDK as defined in the [relevant section of the SPIFFE new projects guideline](https://github.com/spiffe/spiffe/blob/main/NEW_PROJECTS.md)

## Summary

VSecM Go SDK currently remains in-tree as part of a monolithic repository. 

In time, this resulted in several issues including

* The plugin code unnecessarily depending on the in-tree codebase due to lack of isolation,
* Challenges in versioning and tagging,
* Tight coupling
* Increased complexity
* Any SDK-related security advisory affecting the entire repo
* Not being able to easily use different go versions for SDK and main-tree code.

After careful consideration, the VSecM core maintainers have agreed that moving the SDKs out of the main repository will provide better modularity and flexibility for developers. We plan to start by relocating the Go and Rust SDKs to the SPIFFE GitHub organization, with the possibility of adding the Java SDK in the future, based on the feedback and overall developer experience.
This approach aims to streamline development, versioning, and maintenance while ensuring a more focused repository structure for each SDK. We welcome any input or feedback from the committee on this direction.

Here are additional details that may be of use:

## Initial Maintainer List

* Go SDK: [Volkan Ozcelik](https://github.com/v0lkan)
* Rust SDK: [Murat Parlakisik](https://github.com/parlakisik)

In addition to the initial maintainers, [VSecM Code Owners](https://github.com/vmware-tanzu/secrets-manager/blob/main/CODEOWNERS) will closely follow and review the code changes as the SDKs will be actively consumed in VSecM code too.

## Project Purpose and Direction

VMware Secrets Manager has several modes of operation.

* Through a sidecar, where a SPIFFE-aware workload can automatically receive its secrets by the sidecar automatically polling secrets (in a similar fashion to how spiffe helper works)
* Directly using VSecM SDK for additional flexibility and not having to poll for secrets unnecessarily.
* There are other modes of operation that are work in progress too.

VSecM SDKs are useful to allow more fine-grained control and a better development experience.

### Modular Development and Community Engagement

By moving the Go and Rust SDKs out of the VSecM core repository and into the SPIFFE GitHub organization, we are fostering a more modular and community-driven approach. This separation allows developers who are solely focused on SPIFFE and SPIRE to engage with the SDKs independently, without being tied to VSecM's development cycle or structure. This change simplifies contributing, using, and maintaining the SDKs while making it easier for new contributors from the SPIFFE/SPIRE community to collaborate.

#### Easier Access and Contribution

By hosting the SDKs in the SPIFFE GitHub organization, SPIFFE/SPIRE users and contributors can easily find, contribute to, and maintain the Go and Rust SDKs as independent projects. 

This encourages greater community participation and lowers the barrier to entry for developers who are interested specifically in SPIFFE-compatible VSecM SDKs, but who might not be working with VSecM directly.

#### Decoupled Development Cycles

Separating these SDKs from VSecM means that interested developers can evolve and release these SDKs independently of VSecM’s release cadence.

#### Enhanced Transparency and Maintenance

The SPIFFE/SPIRE community will have direct visibility into the SDKs’ development and can provide feedback, report issues, or request features in a more transparent, collaborative environment. This improves maintainability and promotes long-term stability for the Go and Rust SDKs.

## Project Maturity

The SDKs are developed on an "as need" basis. As of now, VSecM Go SDK is mature enough without requiring too much development effort. Rust SDK is still in development, so it will require more work.

Since VSecM constantly evolves, the SDKs will likely evolve with the main project; however, based on former experience, I can say that SDK code does not change too much and it's relatively low-maintenance.

## Alignment with SPIFFE's Mission and Goals

we can re-iterate SPIFFE's Mission as "Establishing Strong Identities for Services in Dynamic, Heterogeneous Environments"

The SPIFFE project is focused on providing secure, scalable service identities that are portable across environments and platforms. One of the core aspects of SPIFFE's mission is to enable workloads to securely authenticate themselves without the need for trusted networks, secret distribution, or human intervention.

#### Facilitating Adoption of SPIFFE Standards

The Go and Rust SDKs are designed to provide developers with easy-to-use libraries that simplify the integration of VSecM (and in extension SPIFFE) into their services. 

**VSecM and SPIFFE are like peanut butter and jelly—each complements the other perfectly**.

This move helps advance the core goal of widespread adoption and integration of SPIFFE standards in real-world, production-grade environments.

#### Supporting Multi-Language Ecosystems

SPIFFE’s mission encompasses diverse, heterogeneous environments. Supporting multiple languages—like Go and Rust—helps achieve SPIFFE's goal of cross-platform, cross-language portability. By officially aligning these SDKs with the SPIFFE GitHub organization, we signal that they are an integral part of the SPIFFE ecosystem, enabling developers to use SPIFFE in various programming environments that reflect the reality of modern software systems.

#### Ensuring Secure, Decoupled Identity Management

The Go and Rust SDKs align with SPIFFE's focus on secure, decoupled identity management by allowing services to integrate SPIFFE identity and authentication mechanisms without embedding insecure secret management practices. These SDKs support workloads in securely obtaining, handling, and verifying identities, helping fulfill SPIFFE’s overarching mission of secure, scalable identity management across dynamic systems.

#### Community-Driven Development

SPIFFE thrives on open, community-driven development. Moving the SDKs under the SPIFFE organization encourages wider participation from the community, which is a core part of SPIFFE’s philosophy. This strengthens the ecosystem by making these SDKs more visible and accessible to the community, inviting contributions that align with SPIFFE’s long-term goals.

#### Modular and Extensible Architecture

One of SPIFFE's goals is to remain modular and extensible, allowing for different integrations and implementations while maintaining core principles. By separating the Go and Rust SDKs into their own repositories, the development of these SDKs becomes more modular, enabling rapid innovation while maintaining alignment with SPIFFE’s goals. This mirrors SPIFFE’s approach of being adaptable to different environments and use cases.

## Governance

Since these projects are relatively small, we do not plan to implement an extensive governance model. Contributions will be reviewed and approved by a core maintainer, ensuring alignment with project goals. All interactions with contributors will be conducted respectfully and in accordance with the SPIFFE Code of Conduct.

The maintainers of VSecM SDK projects and anyone interested from the broader SPIFFE community are encouraged to meet every month at [VMware Secrets Manager Contributor Snyc](https://vsecm.com/community/contributor-hours/).

Along with the monthly community virtual sync-ups, [there is a Slack, and Discord channel that the contributors and the interested individuals from the community can join and discuss topics](https://vsecm.com/community/hello/).

**Comment by kfox1111** [comment]
Seems ok to me.

**Comment by v0lkan** [comment]
Closing since we’ve opened go and rust repos.

I'll do some librarianship (README, LICENSE, DCO, CONTRIBUTING) for them within the next few days.

For the Java and Python SDKs, we'll wait for a while and see how the tiny repo experience for these two (Rust, Go) repos go.
