### ISSUE TITLE
Tiny project: spiffe-step-ssh

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spiffe#311]
I have some shell scripts that let you convert a spiffe identity for a signed ssh host certificate. Been using it on my systems for a while now. This lets you finally solve the ssh unknown host or changed host issues that plague ssh servers.

I'd like to contribute it to spiffe. I started contributing it to https://github.com/spiffe/spire-examples/pull/67 but it seems like it may be a better fit for a tiny project repo.

Its ~78 lines of bash.

Its used in conjunction with https://github.com/spiffe/helm-charts-hardened/pull/198

**Comment by v0lkan** [comment]
We might make a spiffe-utils library repo maybe, and add this script as the first guinea pig. -- as in your personal hacker's toolbox for all things spiffe :) .

**Comment by kfox1111** [comment]
Hmm... That could work, but we also have spire-extras that serves a similar need, and its hard to get anything contributed to it. Having separate repo's seems to help with contributions.

**Comment by v0lkan** [comment]
>  Having separate repo's seems to help with contributions.

Makes sense actually. With a smaller repo, people can find more time and/or will be less overwhelmed.

**Comment by kfox1111** [comment]
Repo created.
