### ISSUE TITLE
No check for CLA in CI

### ISSUE THREAD

**Issue by justincormack** [spiffe/spiffe#49]
The contributing suggests I need to sign the CLA (which I believe my company has already signed), but there is no CI check for this.

As there is an intention of submitting to CNCF, would it be possible to switch from CLA to DCO, which CNCF also accepts, as it is a much lower bar to contribution?

**Comment by drrt** [comment]
Hi Justin, if your commits contain a @mycompany.com email address, and that email address has been verified by GitHub (https://github.com/settings/emails) the CLA checks will pass.

As for CLA vs DCO decision, that's above my pay grade.... it has been discussed, and it may change, but no timeline afaik.

**Comment by justincormack** [comment]
There wasn't a visible check though in my PR... I think @docker.com is ok
but I don't know. I also filled in the Google form but not heard back

**Comment by drrt** [comment]
@docker.com is covered by a Corp CLA. Looking at your PR, our CLA bot checks `user.email`, not `--signoff` - we should probably make the docs more clear on this.

**Comment by caniszczyk** [comment]
Since this is part of CNCF now, we can drop the CLA check and simply use DCO: See #73

**Comment by evan2645** [comment]
We have a DCO bot applied to this repository now, and have moved away from CLA. Closing this issue, thank you for the report.
