### ISSUE TITLE
Java SPIFFE library

### ISSUE THREAD

**Issue by y2bishop2y** [spiffe/spiffe#53]
Need to create the equivalent of the https://github.com/spiffe/go-spiffe library for Java. 

In order to retrieve the SAN URI from an SVID, it is necessary to parse it out with an ASN.1 parser in Java. Having the java-spiffe library can hide all this complexity from a user.

**Comment by az82** [comment]
Bouncycastle provides an API for that: http://grepcode.com/file/repo1.maven.org/maven2/org.bouncycastle/bcprov-jdk15/1.44/org/bouncycastle/x509/extension/X509ExtensionUtil.java

**Comment by evan2645** [comment]
This was done many moons ago and can be found here: https://github.com/spiffe/java-spiffe

Closing this issue
