### ISSUE TITLE
IANA registration for spiffe

### ISSUE THREAD

**Issue by mhausenblas** [spiffe/spiffe#62]
It's a good practice—if not a requirement considered by some—to officially register a URI scheme, see also [BCP35](https://tools.ietf.org/html/bcp35) for guidance.

Since SPIFFE claims the `spiffe` URI scheme, we should kick off the [IANA registration](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml) for this scheme.

**Comment by suniljames** [comment]
@mhausenblas do you think it suffices if we e-mail IANA a link to an updated version of [this SPIFFE page](https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE-ID.md) that include relevant bits as exemplified in the [sgn provisional application](https://www.iana.org/assignments/uri-schemes/prov/sgn)? Process looks to be fairly lightweight.

**Comment by mhausenblas** [comment]
Yes @suniljames, if as per [BCP35, sect 4](https://tools.ietf.org/html/bcp35#section-4) the requirements are fulfilled the rest is really just a couple of mails back and forth. I suggest to think a little bit about who will be the contact; it should be someone trustworthy and reliable and likely to stick around for a bit ;)

**Comment by evan2645** [comment]
Turns out I had opened an issue on this same item some months ago and forgot about it :) #6 

The SPIFFE scheme is now registered with IANA: https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

Thanks for the nudge @mhausenblas
