### ISSUE TITLE
SAN Requirements for Signing Certs appear not to be met by `svid-test`

### ISSUE THREAD

**Issue by banks** [spiffe/spiffe#65]
The current SVID-X509 spec document here

https://github.com/spiffe/spiffe/blob/1e028a071ff517afe9bc21233ec935a91a4f321d/standards/X509-SVID.md#32-signing-certificates

Says

> A signing certificate is itself an SVID. The SPIFFE ID of a signing certificate MUST NOT have a path component, and MUST reside in the trust domain of any leaf SVIDs it issues. A signing certificate MAY be used to issue further signing certificates in the same or different trust domains.

I interpreted that to mean that any signing certificate in the chain MUST have a URI SAN with matching `spiffe://<trust domain>` with no path.

Yet running the reference generator/verifying in `svid-test` generates both Root and Intermediate CAs in t "good" cases that verify correctly with no URI SAN at all and with a DN that is some arbitrary string, e.g. `Issuer: C=US, O=test7.acme.com, CN=RootCA`.

Am I misunderstanding the spec or is `svid-test` not implementing the spec correctly?

**Comment by evan2645** [comment]
Hey @banks - thanks for this. Your interpretation of the spec is correct.

Unfortunately, the `svid-test` suite is badly out of date, and was created before the SPIFFE specification set was formalized. The suite is in need of some TLC, and we have it as an action item to refactor it and bring it in line with X509-SVID. Of course, we would welcome contribution if someone was so inclined to pick up the work :)

I'm going to leave this open as a tracking issue until we can get the suite updated. Very sorry for the confusion here.

**Comment by banks** [comment]
Thanks @evan2645

I can totally understand implementations trailing fast-evolving specs :)

I don’t know if I’ll have time to contribute fixes for the test suite right away but I’m following changes. 

Perhaps a note in the README for `svid-test` would be a good idea in the interim?
