### ISSUE TITLE
Add DCO support

### ISSUE THREAD

**Issue by caniszczyk** [spiffe/spiffe#73]
CNCF projects are expected to follow the DCO.

It's a one click install to enable this for all the SPIFFE repos:
https://github.com/integration/dco

**Comment by suniljames** [comment]
How does the DCO compare/contrast with SPIFFE's existing CLA (individual and corporate)?

**Comment by caniszczyk** [comment]
@suniljames when you're a CNCF project, you essentially have two options:
1) move to the CNCF CLA system
2) just use ALv2+DCO (https://developercertificate.org/)

People find the DCO approach lighter weight as it just requires contributors to sign off their commits (i.e., git commit -s) and the checking is built into GitHub if you install it via the link I posted.

**Comment by caniszczyk** [comment]
@suniljames would be great to make this transition by the end of this week

**Comment by suniljames** [comment]
Got it. Thanks for clarifying

**Comment by evan2645** [comment]
The DCO integration has been added, and the SPIFFE CLAbot has been removed. Thanks @caniszczyk
