### ISSUE TITLE
Adopt CII Badge

### ISSUE THREAD

**Issue by caniszczyk** [spiffe/spiffe#74]
As part of becoming a CNCF project, we expect projects to part take in the CII Badging program and ensure you pass: https://bestpractices.coreinfrastructure.org/en

This involves defining some security best practices like a disclosure program etc.

**Comment by ajessup** [comment]
For spiffe/spiffe the CII badge isn't relevant, but is for spiffe/spire and has been completed (see https://github.com/spiffe/spire/blob/master/README.md). The requisite best practices were reviewed and implemented as part of SPIFFE/SPIRE's graduation to Incubation.
