### ISSUE TITLE
Add ADOPTERS.md

### ISSUE THREAD

**Issue by caniszczyk** [spiffe/spiffe#78]
Add an ADOPTERS file that lists people who are using SPIFFE in interesting ways.

Cargo cult away here: https://github.com/linkerd/linkerd/blob/master/ADOPTERS.md

This is a requirement of CNCF Graduation down the line but it's better to get this done earlier imho, you never know who will come out of the wood work :)

**Comment by ajessup** [comment]
This has been completed for the SPIRE project. https://github.com/spiffe/spire/blob/master/ADOPTERS.md
