### ISSUE TITLE
Integrate with spiffle

### ISSUE THREAD

**Issue by tianxiaoliang** [spiffe/spiffe#83]
Hi I am the owner of this project https://github.com/ServiceComb/go-chassis
we are about to integrate with Istio auth, but I found this solution here, so do you have a example about how spiffle work with Istio, that will be great for us to consider about how to integrate with Istio

**Comment by ajessup** [comment]
Hey there - you'd have to check with the Istio project about what interfaces Istio Auth exposes. However you can ensure compatibility with SPIRE and other SPIFFE implementations by retrieving identities with the [SPIFFE Workload API](https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE_Workload_API.md).

**Comment by ajessup** [comment]
Hey there - just following up. Could you give an example of what SPIFFE/Istio intergration you would like to see?
